### ISSUE TITLE
SMuRF input data type

### ISSUE THREAD

**Issue by caokai001** [skandlab/SMuRF#38]
Hi !
I would like to ask, the data types downloaded by TCGA are different from the four types recommended by this software package `MuTect2, FreeBayes, VarDict and VarScan`. so can I use use 2 or 3 type somatics data to train model and improve the accuracy of somatic mutation.

Thanks!   by caokai
![image](https://user-images.githubusercontent.com/33218753/70991336-39b47380-2102-11ea-92e9-81d2526ea3e9.png)

**Comment by tyler5huang** [comment]
Hi caokai,

Unfortunately no for now as the software package uses exactly 4 callers which are important for the overall accuracy of the training model. 

If you are using TCGA data, you can try to use the simple consensus method to find mutations called by at least two callers rather than this software. Our evaluation shows MuTect2 is a fairly accurate caller on its own as well.

Regards,
Tyler

**Comment by caokai001** [comment]
ok, thanks for your reply！
